---
  AWSTemplateFormatVersion: "2010-09-09"
  Resources:
    AutospottingPolicy:
      Type: "AWS::IAM::Policy"
      Properties:
        PolicyDocument:
          Statement:
            -
              Action:
                - "autoscaling:DescribeAutoScalingGroups"
                - "autoscaling:DescribeLaunchConfigurations"
                - "autoscaling:AttachInstances"
                - "autoscaling:DetachInstances"
                - "autoscaling:DescribeTags"
                - "autoscaling:UpdateAutoScalingGroup"
                - "cloudformation:DescribeStacks"
                - "ec2:CreateTags"
                - "ec2:DescribeInstances"
                - "ec2:DescribeRegions"
                - "ec2:DescribeSpotPriceHistory"
                - "ec2:RunInstances"
                - "ec2:TerminateInstances"
                - "iam:PassRole"
                - "iam:CreateServiceLinkedRole"
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Effect: "Allow"
              Resource: "*"
        PolicyName: "AutospottingPolicy"
        Roles:
          -
            Ref: "AutospottingRole"
    AutospottingRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            -
              Action: "sts:AssumeRole"
              Effect: "Allow"
              Principal:
                Service:
                  - "ecs-tasks.amazonaws.com"
